services:
  mongodb:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      MONGODB_URI: mongodb+srv://Harmi:Harmiai@cluster0.v3vbitv.mongodb.net/restaurant_ar_menu?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      mongodb:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - api

volumes:
  mongo_data:
